apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tc7vo1g86-dotnet-basic
  janus-idp.io/tekton: tc7vo1g86-dotnet-basic
  backstage.io/kubernetes-id: tc7vo1g86-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tc7vo1g86-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
