apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: tc7vo1g86-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/tc7vo1g86-dotnet-basic-gitops